### ISSUE TITLE
Selling more than ~5 items kicks you from the game

### ISSUE THREAD

**Issue by arcynum** [arcynum/wow-vanilla-addons#6]
Need to implement a wait function so that the game doesn't kick you when you sell too many grey items.

http://wowwiki.wikia.com/wiki/Wait

**Comment by stevenlomas** [comment]
[Added an 80ms delay for each sold item.](https://github.com/arcynum/wow-vanilla-addons/commit/f01aed6e52e2cbee905249de9c25e70a6ac9eee1)
